flask_blog/app/app/posts/blueprint.py
from flask import Blueprint, render_template
from models import *
from flask import request, url_for, redirect, flash
from App import db, app
from sqlalchemy import or_
from .forms import PostForm
from werkzeug.utils import secure_filename
from flask_login import login_required, login_user, current_user, logout_user

import os

posts = Blueprint('posts', __name__, template_folder="templates")
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@posts.route('/login')
def login():
    return render_template('posts/login.html')

@posts.route('/login', methods=['POST'])
def login_post():
    i = 0
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    pwd = hashlib.md5(password.encode()).hexdigest()
    
    user = User.query.filter_by(email=email).first()
    hashed_password_in_db = user.password if user else None
    if not hashed_password_in_db:
        flash('Invalid email or password')
        return redirect(url_for('posts.login'))
    elif pwd != hashed_password_in_db:
        flash('Invalid email or password')
        return redirect(url_for('posts.login'))
    else:
        login_user(user, remember=True)
        return render_template('posts/page.html')

@posts.route('/signup')
def signup():
    return render_template('posts/signup.html')

@posts.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    first_name = request.form.get('first_name')
    last_name = request.form.get('last_name')
    password = request.form.get('password')
    
    user = User.query.filter_by(email=email).first()
    if user:
        flash('User already exist!!!')
        return redirect(url_for('posts.signup'))
    new_user = User(email=email, first_name=first_name, last_name=last_name, password=password)
    db.session.add(new_user)
    new_role = Role.query.filter_by(name='user').first()
    if new_role:
        new_user.roles.append(new_role)
    db.session.commit()
    return redirect(url_for('posts.login'))
    
@posts.route('/<userid>')
def dashboard(userid):
    return redirect(url_for("posts.authenticated", userid=userid))

@posts.route('/profile/<userid>/')
@login_required
def profile(userid):
    return render_template("posts/profile.html")

@posts.route('/profile/', methods=['POST'])
@login_required
def profile_post():
    pass

@posts.route('/logout')
@login_required
def logout():
    logout_user()
    return render_template("posts/page.html")











@posts.route('/<userid>')
def authenticated(userid):
    user = User.query.filter_by(userid=userid).first()
    login_user(user, remember=True)
    return redirect(url_for('posts.post_list'))

# routes to /blog
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def post_create():
    user = None
    if current_user.is_authenticated:
        user = User.query.filter_by(email=current_user.email).first()
    form = PostForm()
    filepath = None
    taglist = []
    t_ = None
    p_ = None
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        image = request.files['filepath']
        try:
            taglist = request.form.getlist("mycheckbox")
        except:
            taglist = []
        if image and allowed_file(image.filename):
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config['UPLOAD_FOLDER'] + '/static/', filename))
            filepath = filename
        post = Post(title=title, body=body, filepath=filepath, user_id="f6115d2d-50ac-4bc5-8f15-1d555cd90562")
        db.session.add(post)
        print(taglist)
        if len(taglist) > 0:
            for tag in taglist:
                t_ = Tag.query.filter_by(title=tag).first()
                post.tags.append(t_)
                user.posts.append(post)
        db.session.commit()
                
        return redirect(url_for('posts.post_list'))
    tags = Tag.query.all()
    return render_template('posts/post_create.html', form=form, tags=tags)


@posts.route('/')
@login_required
def post_list():
    user = None
    if current_user.is_authenticated:
        user = User.query.filter_by(email=current_user.email).first()
    i = 0
    q = request.args.get('q')
    if q:
        postlist = Post.query.filter(or_(Post.title.contains(q), Post.body.contains(q)),
                                     Post.user_id == current_user.userid)
# postlist = Post.query.filter(Post.title.contains(q) |
                                  #   Post.body.contains(q)) """
    else:
        postlist = Post.query.filter_by(user_id=current_user.userid).order_by(Post.created.desc())

    
    print(postlist)
    
    page = request.args.get("page")
    #localhost:5000/blog?page=7478
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    try:
        pages = postlist.paginate(page=page, per_page=3)
    except:
        if (postlist.count() % 3 != 0):
            count =  int((postlist.count() / 3)) + 1
        else:
            count = (postlist.count() / 3)

        pages = postlist.paginate(page=count, per_page=3)

    
    return render_template('posts/post_list.html', postlist=postlist, i=i, pages=pages)

#route to specific post details
@posts.route('/<slug>/', methods=['GET'])
def post_details(slug):
    postdetail = Post.query.filter(Post.slug==slug).first()
    return render_template('posts/post_detail.html', postdetail=postdetail)

#route to specific post details
@posts.route('tags/<slug>')
def tag_details(slug):
    i = 0
    tags = Tag.query.filter(Tag.slug==slug).first()
    return render_template('posts/tag_detail.html', tags=tags, i=i)

@posts.route('/<slug>/edit', methods=["POST", "GET"])
def post_update(slug):
    post = Post.query.filter(Post.slug==slug).first()
    taglist = []
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        filepath = None
        image = None
        form.populate_obj(post)
        title = request.form.get('title')
        body = request.form.get('body')
        try:
            taglist = request.form.getlist("mycheckbox")
        except:
            taglist = []
        try:
            image = request.files['filepath']
        except:
            image = None
        if image != None  and allowed_file(image.filename):
            if post.filepath:
                if os.path.exists(os.path.join(app.config['UPLOAD_FOLDER'] + '/static/', post.filepath)):
                    os.remove(os.path.join(app.config['UPLOAD_FOLDER'] + '/static/', post.filepath))
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config['UPLOAD_FOLDER'] + '/static/', filename))
            filepath = filename
        post.title = title
        post.body = body
        post.filepath = post.filepath
        if filepath:
            post.filepath = filepath
        print(taglist)
        for tag in post.tags:
            post.tags.remove(tag)
        if len(taglist) > 0:
            for tag in taglist:
                t_ = Tag.query.filter_by(title=tag).first()
                post.tags.append(t_)
        db.session.commit()
        return redirect(url_for("posts.post_details", slug=post.slug))
    form = PostForm(obj=post)
    form.filepath.data = post.filepath
    tags = Tag.query.all()
    return render_template("posts/edit.html", post=post, form=form, tags=tags)


def save_image(image):
    if image:
        filename = secure_filename(image.filename)
        image.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        return filename  # Return the filename for storing in your database
    return None

flask_blog/app/posts/blueprint.py
from flask import Blueprint, render_template
from models import *
from flask import request, url_for, redirect, flash
from App import db, app
from sqlalchemy import or_
from .forms import PostForm
from werkzeug.utils import secure_filename
from flask_login import login_required, login_user, current_user, logout_user

import os

posts = Blueprint('posts', __name__, template_folder="templates")
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@posts.route('/login')
def login():
    return render_template('posts/login.html')

@posts.route('/login', methods=['POST'])
def login_post():
    i = 0
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    pwd = hashlib.md5(password.encode()).hexdigest()
    
    user = User.query.filter_by(email=email).first()
    hashed_password_in_db = user.password if user else None
    if not hashed_password_in_db:
        flash('Invalid email or password')
        return redirect(url_for('posts.login'))
    elif pwd != hashed_password_in_db:
        flash('Invalid email or password')
        return redirect(url_for('posts.login'))
    else:
        login_user(user, remember=True)
        return redirect(url_for('index'))

@posts.route('/signup')
def signup():
    return render_template('posts/signup.html')

@posts.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    first_name = request.form.get('first_name')
    last_name = request.form.get('last_name')
    password = request.form.get('password')
    
    user = User.query.filter_by(email=email).first()
    if user:
        flash('User already exist!!!')
        return redirect(url_for('posts.signup'))
    new_user = User(email=email, first_name=first_name, last_name=last_name, password=password)
    db.session.add(new_user)
    new_role = Role.query.filter_by(name='user').first()
    if new_role:
        new_user.roles.append(new_role)
    db.session.commit()
    return redirect(url_for('posts.login'))
    
@posts.route('/<userid>')
def dashboard(userid):
    return redirect(url_for("posts.authenticated", userid=userid))

@posts.route('/profile/<userid>')
@login_required
def profile(userid):
    return render_template("posts/profile.html", userid=userid)

@posts.route('/profile/', methods=['POST'])
@login_required
def profile_post():
    filepath = None
    image = None
    taglist = []
    t_ = None
    p_ = None
    if request.method == 'POST':
        user = User.query.filter_by(userid=current_user.userid).first()
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        About = request.form.get('instagram')
        website = request.form.get('website')
        gitup = request.form.get('gitup')
        facebook = request.form.get('facebook')
        linkedin = request.form.get('linkedin')
        youtube = request.form.get('youtube')
        twitter = request.form.get('twitter')
        try:
            image = request.files['filepath']
        except:
            image = None
        if image != None  and allowed_file(image.filename):
            if user.filepath:
                if os.path.exists(os.path.join(app.config['UPLOAD_FOLDER'] + '/static/', user.filepath )):
                    os.remove(os.path.join(app.config['UPLOAD_FOLDER'] + '/static/', user.filepath))
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config['UPLOAD_FOLDER'] + '/static/', 'userblog_' + filename))
            filepath = 'userblog_' + filename
        user.filepath = user.filepath
        if filepath:
            user.filepath = filepath
        user.first_name = first_name
        user.last_name = last_name
        user.instagram = About
        user.website = website
        user.gitup = gitup
        user.facebook = facebook
        user.linkedin = linkedin
        user.youtube = youtube
        user.twitter = twitter
        db.session.commit()
        flash('Record updated successfully')
        return redirect(url_for("posts.profile", userid=current_user.userid))
    
@posts.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))




@posts.route('/<postid>/delete')
def post_delete(postid):
    post = Post.query.filter_by(postid=postid).first()
    if post:
        db.session.delete(post)
        db.session.commit()
    return redirect(url_for('posts.post_list', userid=current_user.userid))

@posts.route('/reset', methods=['GET'])
def reset():
    return render_template("posts/reset.html")

@posts.route('/reset', methods=['POST'])
def reset_post():
    email = request.form.get('email')
    password = request.form.get('password')
    confirmpassword = request.form.get('confirmpassword')
    user = User.query.filter_by(email=email).first()
    if not user:
        flash("User doesnt exist!!")
        return redirect(url_for('posts.reset'))
    if password != confirmpassword:
        flash("Password doesnt match!!")
        return redirect(url_for('posts.reset'))
    if user:
        user.password = password
        db.session.commit()
        logout_user()
    return redirect(url_for('posts.login'))





@posts.route('/<userid>')
def authenticated(userid):
    user = User.query.filter_by(userid=userid).first()
    login_user(user, remember=True)
    return redirect(url_for('posts.post_list'))

# routes to /blog
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def post_create():
    user = None
    if current_user.is_authenticated:
        user = User.query.filter_by(email=current_user.email).first()
    form = PostForm()
    filepath = None
    taglist = []
    t_ = None
    p_ = None
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')
        image = request.files['filepath']
        try:
            taglist = request.form.getlist("mycheckbox")
        except:
            taglist = []
        if image and allowed_file(image.filename):
            filename = secure_filename(image.filename)
            image.save(os.path.join(app.config['UPLOAD_FOLDER'] + '/static/', filename))
            filepath = filename
        post = Post(title=title, body=body, filepath=filepath, user_id="f6115d2d-50ac-4bc5-8f15-1d555cd90562")
        db.session.add(post)
        print(taglist)
        if len(taglist) > 0:
            for tag in taglist:
                t_ = Tag.query.filter_by(title=tag).first()
                post.tags.append(t_)
                user.posts.append(post)
        db.session.commit()
                
        return redirect(url_for('posts.post_list', userid=current_user.userid))
    tags = Tag.query.all()
    return render_template('posts/post_create.html', form=form, tags=tags)


@posts.route('/<userid>/')
def post_list(userid):
    user = None
    if current_user.is_authenticated:
        user = User.query.filter_by(email=current_user.email).first()
    user_ = User.query.filter_by(userid=userid).first()
    i = 0
    q = request.args.get('q')
    if q:
        postlist = Post.query.filter(or_(Post.title.contains(q), Post.body.contains(q)),
                                     Post.user_id == userid)
# postlist = Post.query.filter(Post.title.contains(q) |
                                  #   Post.body.contains(q)) """
    else:
        postlist = Post.query.filter_by(user_id=userid).order_by(Post.created.desc())
    
    page = request.args.get("page")
    #localhost:5000/blog?page=7478
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    try:
        pages = postlist.paginate(page=page, per_page=3)
    except:
        if (postlist.count() % 3 != 0):
            count =  int((postlist.count() / 3)) + 1
        else:
            count = (postlist.count() / 3)

        pages = postlist.paginate(page=count, per_page=3)

    
    return render_template('posts/post_list.html', postlist=postlist, i=i, pages=pages, user_=user_)

#route to specific post details
@posts.route('/<slug>/<userid>', methods=['GET'])
def post_details(slug, userid):
    postdetail = Post.query.filter(Post.slug==slug, Post.user_id==userid).first()
    user_ = User.query.filter_by(userid=userid).first()
    return render_template('posts/post_detail.html', postdetail=postdetail, user_=user_)

#route to specific post details
@posts.route('tags/<slug>/<userid>')
def tag_details(slug, userid):
    i = 0
    tags = Tag.query.filter(Tag.slug==slug).first()
    page = request.args.get("page")
    q = request.args.get('q')
    if q:
        postlist = Post.query.join(Post.tags).filter_by(slug=slug).filter(
            (Post.title.contains(q)) | (Post.body.contains(q))
        )
    else:
        postlist = Post.query.join(Post.tags).filter_by(slug=slug)
    
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    try:
        pages = postlist.paginate(page=page, per_page=3)
    except:
        if (postlist.count() % 3 != 0):
            count =  int((postlist.count() / 3)) + 1
        else:
            count = (postlist.count() / 3)

        pages = postlist.paginate(page=count, per_page=3)
    
    user_ = User.query.filter_by(userid=userid).first()
    return render_template('posts/tag_detail.html', tags=tags, pages=pages, i=i, user_=user_)

@posts.route('/<slug>/<userid>/edit', methods=["POST", "GET"])
@login_required
def post_update(slug, userid):
    post = Post.query.filter(Post.slug==slug, Post.user_id==userid).first()
    taglist = []
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        filepath = None
        image = None
        form.populate_obj(post)
        title = request.form.get('title')
        body = request.form.get('body')
        try:

flask_blog/app/posts/templates/posts/edit.html
{% extends 'layout.html' %}


{% block title %}
    <h3>New Post</h3>
{% endblock title %}

{% block contents %}
<h4> Edit "{{ post.title }}"</h4>
<hr>

<form action="{{ url_for('posts.post_update', slug=post.slug, userid=post.user_id) }}" method="POST" enctype="multipart/form-data">

    <div class="amenities">
        Select tag(s):
        <h4> </h4>
        <div class="popover">
          <ul>
            {% for tag in tags %}
            {% if tag.title and tag in post.tags %}
            <li> <input type="checkbox" checked="true" name="mycheckbox" value="{{ tag.title }}" data-id="{{ tag.id }}" data-name="{{ tag.title }}">
              {{ tag.title }}
                </li>
                {% else %}
                <li> <input type="checkbox" name="mycheckbox" value="{{ tag.title }}" data-id="{{ tag.id }}" data-name="{{ tag.title }}">
                    {{ tag.title }}
                      </li>
                {% endif%}
            {% endfor %}
          </ul>
        </div>
      </div>
      <br>


    {% for field in form %}
    <div class="form-group">
   {{ field.label(style="font-size: 20px") }}
   {% if field.type == 'FileField' %}
   <div>{{ field(class='form-control', style="width: 650px") }}</div>
   {% elif field.type == 'TextAreaField' %}
   {{ field(class='form-control', style="height: 300px") }}
   {% else %}
   {{ field(class='form-control') }}
   {% endif %}
   <br>
    </div>
    {% endfor %}
    <script>
        CKEDITOR.replace( 'body' );
    </script>
    <button class="btn btn-primary">submit</button>
</form>
<link rel="stylesheet" href="{{ url_for('static', filename='styles/tags.css') }}">
<script src="/static/scripts/tags.js"></script>
{% endblock contents %}

flask_blog/app/posts/templates/posts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #f4f4f4;
        }

        .login-container {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            margin-top: 100px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: #fff;
        }
        
    </style>
</head>
<body>
  
    <div class="container login-container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-danger custom-alert hidden">
            {{ messages[0] }}
        </div>
        {% else %}
        <div class="alert alert-primary custom-alert">
            Please login to access the main page
        </div>
        {% endif %}
        {% endwith%}

        <h2 class="text-center">MyBlogText</h2>
        <hr>
        <form action="{{url_for('posts.login_post')}}" method="POST" >
            <div class="form-group">
                <label for="email">Email address:</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Enter email" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Enter password" required>
            </div>

            <div class="form-group">
                <label for="remember">
                    <input type="checkbox" name="remember" id="remember"/>
                    Remember me</label>
               </div><div  style="float: left;">
                    <a href="{{ url_for('index') }}" class="btn btn-light btn-sm">Back to Home</a>
                </div> 
<div  style="text-align: right;"">
            <button type="submit"  class="btn btn-primary">Login</button>
            <a href="{{ url_for('posts.reset') }}" class="btn btn-light btn-sm">forgot password</a>
        </div> 
        </form>
    </div>

    <!-- Include Bootstrap JS and Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

flask_blog/app/posts/templates/posts/login2.html
<!DOCTYPE html>
<html>
        <head>
                <meta charset="utf-8">
                <title>CKEditor</title>
                <script src="https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js"></script>
        </head>
        <body>
                <textarea name="editor1"></textarea>
                <script>
                        CKEDITOR.replace( 'editor1' );
                </script>
        </body>
</html>

flask_blog/app/posts/templates/posts/page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto&family=Sacramento&display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <link rel="stylesheet" href="/static/styles/style.css" />
  </head>
  <body>
    <div class="main-container">
      <video autoplay loop muted>
        <source src="videos/bg.mp4" type="video/mp4" />
      </video>

      <div class="bg-overlay"></div>

      <nav>
        <div class="logo">
          <a href="#">MyBlogText</a>
        </div>

        <!-- <ul class="menu-items">
          <li>
            <a href="#">DASHBOARD</a>
          </li>

          <li>
            <a href="#">SIGN UP</a>
          </li>
          
          <li>
            <a href="#">LOG IN</a>
          </li>
          <li>

            <a href="#">LOG OUT</a>
          </li>
        </ul> -->
        <ul class="menu-items">
        {% if not current_user.is_authenticated %}
        <li>
        <a href="{{ url_for('posts.login') }}">Login</a>
        </li>
        {% endif %}
        {% if current_user.is_authenticated %}
        <li>
        <a href="{{ url_for('posts.post_list', userid=current_user.userid) }}">Dashboard</a>
        </li>
        {% endif %}
        {% if not current_user.is_authenticated %}
        <li>
        <a href="{{ url_for('posts.signup') }}">Signup</a>
        </li>
        {% endif %}
        
        {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('posts.logout') }}">Logout</a>
          </li>
        {% endif %}
      </ul>
        <div class="menu-button">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M4 8h16M4 16h16"
            />
          </svg>
        </div>
      </nav>

      <header class="hero-section">
        <h1>My Blogger Text</h1>
        <article>

        </article>
        <br>
       <br>
        <p>Welcome to MyBlogText - Your Ultimate Blogging Platform </p>
 <br>
        <p>Elevate Your Writing Experience</p>
<br>
        <p>At MyBlogText, we believe that every voice deserves to be heard. Our platform is designed to empower everyone like you
        to express your thoughts, share your stories, and connect with a global audience. Whether you're a seasoned writer or
        just starting your writing journey, MyblogText provides the perfect space to showcase your creativity</p>
<br>
{% if not current_user.is_authenticated %}
<p>
  Click below.
</p>
{% else %}
<p> Go to your Dashboard!!  </p>
{% endif %}
        {% if not current_user.is_authenticated %}
        <a href="{{ url_for('posts.login') }}" class="btn">GET STARTED</a>
        {% else %}
        <a href="{{ url_for('posts.post_list', userid=current_user.userid) }}" class="btn">Welcome {{ current_user.first_name }}</a>
        {% endif %}
      </header>

      <div class="social">
        <a href="#">
          <i class="fab fa-twitter"></i>
        </a>

        <a href="git@github.com:Abstaina44/ALX-Portfolio-Project.git">
          <i class="fab fa-github"></i>
        </a>

        <a href="#">
          <i class="fab fa-instagram"></i>
        </a>
      </div>
    </div>

    <div class="mobile-menu-items">
      <div class="close-button">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-6 w-6"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M6 18L18 6M6 6l12 12"
          />
        </svg>
      </div>

      <ul class="menu-items">
        <li>
          <a href="#">sign up</a>
        </li>

        <li>
          <a href="#">DASHBOARD</a>
        </li>

        <li>
          <a href="#">About</a>
        </li>

        <li>
          <a href="#">Contact</a>
        </li>
      </ul>
    </div>

    <script src="/static/scripts/main.js"></script>
  </body>
</html>

flask_blog/app/posts/templates/posts/post_create.html
{% extends 'layout.html' %}


{% block title %}
    <h3>New Post</h3>
{% endblock title %}

{% block contents %}
<h4> Create Post</h4>
<hr>

<form action="{{ url_for('posts.post_create') }}" method="POST" enctype="multipart/form-data">

    <div class="amenities">
        Select tag(s):
        <h4> </h4>
        <div class="popover">
          <ul>
            {% for tag in tags %}
            {% if tag.title %}
            <li> <input type="checkbox" name="mycheckbox" value="{{ tag.title }}" data-id="{{ tag.id }}" data-name="{{ tag.title }}">
              {{ tag.title }}
                </li>
                {% endif%}
            {% endfor %}
          </ul>
        </div>
      </div>
      <br>
    {% for field in form %}
    <div class="form-group">
   {{ field.label(style="font-size: 20px") }}
   {% if field.type == 'TextAreaField' %}
   {{ field(class='form-control', style="height: 300px") }}
   {% else %}
   {{ field(class='form-control') }}
   {% endif %}
   <br>
    </div>
    {% endfor %}
    <script>
        CKEDITOR.replace( 'body' );
    </script>
    <button class="btn btn-primary">submit</button>
</form>
<link rel="stylesheet" href="{{ url_for('static', filename='styles/tags.css') }}">
<script src="/static/scripts/tags.js"></script>
{% endblock contents %}